spring:
  # thymeleaf config
  thymeleaf:
    cache: false
  # db config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 11111abc
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    hikari:
      pool-name: DateHikariCP
      # 最小链接数
      minimum-idle: 5
      # 空闲链接最大存活时间，默认60000ms
      #idle-timeout: 180000
      # 最大链接数 默认10
      maximum-pool-size: 10
      # 从连接池返回的的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活 默认30分钟
      #max-lifetime: 180000
      # 连接超时时间
      connection-timeout: 300000
      # 测试连接是否可用的查询语句 心跳测试
      connection-test-query: SELECT 1

# Mybatis-plus配置
mybatis-puls:
  # 配置Mapper.xml配置文件
  mapper-locaitons: classpath*://mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名
  type-aliases-package: com.kang.seckilldemo.pojo

# myBatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.example.sekilldemo.mapper: debug
